openapi: 3.0.0
info:
  title: 얼굴검출
  version: '1.0'
  description: |-
    **서비스 소개**

    컴트루테크놀로지에서 독자적으로 개발한 얼굴인식 신경망을 통해 동영상, 사진, 이미지 내에서 얼굴 영역을 검출합니다.<br>
    KISA 바이오인식(얼굴인식) 인증을 획득한 신경망으로, 보다 신뢰 높은 얼굴인식을 지원합니다.

    **서비스 특징**

    인식우선 모드 : 저화질의 해상도의 얼굴도 우선적으로 인식합니다.

    분석우선 모드 : 고화질의 얼굴을 인식하여 얼굴 분석 서비스를 연동하여 데이터를 추출할 수 있습니다.
  contact:
    email: ask@comtrue.com
    url: 'https://cometrue.ai'
    name: cometrue.ai AI API
  termsOfService: 'https://cometrue.ai/index.php/ai-api-terms-of-service/'
servers:
  - {}
paths:
  /face-detection:
    post:
      summary: 얼굴검출
      operationId: post-facedetection
      responses:
        '200':
          description: |-
            OK

            정상응답
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    Template: ''
                    ROI:
                      - index: 0
                        x: 530
                        'y': 87
                        width: 119
                        height: 152
                        text: ''
                        tag: face
                        language: ''
                properties:
                  Template:
                    type: string
                  ROI:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    description: 얼굴 영역 리스트
                    items:
                      type: object
                      properties:
                        index:
                          type: number
                          description: '리스트 인덱스 '
                        x:
                          type: number
                          description: 얼굴 영역의 왼쪽 상단 x 좌표
                        'y':
                          type: number
                          description: 얼굴 영역의 왼쪽 상단 y 좌표
                        width:
                          type: number
                          description: 얼굴 영역 너비
                        height:
                          type: number
                          description: 얼굴 영역 높이
                        text:
                          type: string
                          description: ''
                        tag:
                          type: string
                          description: ''
                          pattern: face
                        language:
                          type: string
                          description: ' '
              examples:
                결과:
                  value:
                    Template: ''
                    ROI:
                      - index: 0
                        x: 482
                        'y': 120
                        width: 223
                        height: 317
                        text: ''
                        tag: face
                        language: ''
                      - index: 1
                        x: 885
                        'y': 132
                        width: 216
                        height: 293
                        text: ''
                        tag: face
                        language: ''
                      - index: 2
                        x: 1292
                        'y': 131
                        width: 203
                        height: 294
                        text: ''
                        tag: face
                        language: ''
                      - index: 3
                        x: 1694
                        'y': 109
                        width: 225
                        height: 338
                        text: ''
                        tag: face
                        language: ''
                      - index: 4
                        x: 99
                        'y': 132
                        width: 215
                        height: 311
                        text: ''
                        tag: face
                        language: ''
                      - index: 5
                        x: 496
                        'y': 524
                        width: 221
                        height: 306
                        text: ''
                        tag: face
                        language: ''
                      - index: 6
                        x: 867
                        'y': 523
                        width: 229
                        height: 310
                        text: ''
                        tag: face
                        language: ''
                      - index: 7
                        x: 1680
                        'y': 532
                        width: 226
                        height: 293
                        text: ''
                        tag: face
                        language: ''
                      - index: 8
                        x: 67
                        'y': 535
                        width: 229
                        height: 303
                        text: ''
                        tag: face
                        language: ''
                      - index: 9
                        x: 1284
                        'y': 524
                        width: 218
                        height: 324
                        text: ''
                        tag: face
                        language: ''
                      - index: 10
                        x: 478
                        'y': 919
                        width: 231
                        height: 316
                        text: ''
                        tag: face
                        language: ''
                      - index: 11
                        x: 1285
                        'y': 931
                        width: 217
                        height: 308
                        text: ''
                        tag: face
                        language: ''
                      - index: 12
                        x: 1695
                        'y': 925
                        width: 223
                        height: 320
                        text: ''
                        tag: face
                        language: ''
                      - index: 13
                        x: 87
                        'y': 935
                        width: 213
                        height: 301
                        text: ''
                        tag: face
                        language: ''
                      - index: 14
                        x: 871
                        'y': 937
                        width: 220
                        height: 296
                        text: ''
                        tag: face
                        language: ''
        '400':
          $ref: '#/components/responses/400'
        '401':
          description: |-
            Unauthorized

            허가되지 않은 사용자의 접근
        '409':
          $ref: '#/components/responses/409'
        '500':
          description: |-
            Internal Server Error

            서버가 유지보수 중이거나 응답할 수 없는 상태
      description: 얼굴을 인식하여 인식한 사각형 영역의 리스트를 제공합니다.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                image:
                  type: string
                  minLength: 1
                  description: base64로 인코딩 한 스트링 or http URL
                model_type:
                  type: integer
                  description: 모델타입
                  enum:
                    - 1
                    - 2
              required:
                - image
                - model_type
            examples:
              Base64 Example:
                value:
                  image: iVBORw0KGgoAAAANSUhEUgAACbEAAA2zCAYAAADce6KLAAAA....
              URL Example:
                value:
                  id_type: jumin
                  image: 'https://www.cometrue.ai/data/license.jpg'
                  is_url: true
        description: ''
      security:
        - api_key: []
      x-internal: false
    parameters: []
components:
  schemas: {}
  securitySchemes:
    api_key:
      name: api_key
      type: apiKey
      in: query
      description: api.cometrue.ai에서 발급받은 API key
  responses:
    '400':
      description: |
        Bad Request

        사용자가 키를 잘못 입력하였거나, 값에 문제가 있을때

        <details markdown="1">
        <summary>에러메세지</summary>
        "image: not provided"<br>
        "image base64 decode error"<br>
        "Image cannot be read"<br>
        "Image is too small to process"<br>
        "image: property in this field does not match. base64 or url."<br>
        "Image is empty"<br>
        "model_type: not provided."<br>
        </details>
      content:
        application/json:
          schema:
            description: ''
            type: object
            properties:
              message:
                type: string
                minLength: 1
            required:
              - message
          examples:
            image not given:
              value:
                message: 'image: not provided'
            base64 decoding of the image failed:
              value:
                message: image base64 decode error
            Image not readable:
              value:
                message: Image cannot be read
            Query image is too small to process:
              value:
                message: Image is too small to process
            image property does not match:
              value:
                message: 'image: property in this field does not match. base64 or url.'
            image empty:
              value:
                message: Image is empty
            model_type not provided:
              value:
                message: 'model_type: not provided.'
    '409':
      description: |-
        Conflict

        서버에서의 처리 중 에러

        <details markdown="1">
        <summary>에러메세지</summary>
        "Onnx runtime error: 100"<br>
        "Std Exception: 101"<br>
        "OpenCV error: 100"<br>
        "text detection error: 201": cannot find text<br>
        "text detection error: 202": Vertex detection error<br>
        "text detection error: 203": cannot find square<br>
        "text detection error: 204": not enough to be square<br>
        "text detection error: 206": not enough similar area<br>
        "text detection error: 207": not enough contour<br>
        "text detection error: 208": not enough group<br>
        "object detection error: 209": cannot find object<br>
        "Json decode error"
        </details>
      content:
        application/json:
          schema:
            description: ''
            type: object
            properties:
              message:
                type: string
            required:
              - message
          examples:
            Vertex detection error:
              value:
                message: 'text detection error: 202'
            Text detection error:
              value:
                message: text detection error
            //OCR error:
              value:
                message: text recognition error
            //Matching error:
              value:
                message: matching error
            onnxexception:
              value:
                message: 'Onnx runtime error: 100'
            stdexception:
              value:
                message: 'Std Exception: 101'
            cvexception:
              value:
                message: 'OpenCV error: 100'
            cannot find text:
              value:
                message: 'text detection error: 201'
            cannot find square:
              value:
                message: 'text detection error: 203'
            not enough to be square:
              value:
                message: 'text detection error: 204'
            not enough contour:
              value:
                message: 'text detection error: 207'
            not enough group:
              value:
                message: 'text detection error: 208'
            cannot find object:
              value:
                message: 'object detection error: 209'
            json decode error:
              value:
                message: Json decode error
            not enough similar area:
              value:
                message: 'text detection error: 206'
