openapi: 3.0.0
info:
  title: IDliveness
  version: '1.0'
  description: ~~ ~~입니다
  contact:
    email: ask@comtrue.com
    url: 'https://cometrue.ai'
    name: cometrue.ai AI API
  termsOfService: 'https://cometrue.ai/index.php/ai-api-terms-of-service/'
servers:
  - description: Cometrue
paths:
  /api/v1/id/liveness:
    post:
      summary: IdLiveness
      operationId: post-idliveness
      responses:
        '200':
          description: |-
            OK

            정상응답
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    result: 1
                    fakeScore: 0.476456
                    realScore: 0.527431
                    detectSquareErr: 0
                properties:
                  result:
                    type: number
                    description: ' '
                  fakeScore:
                    type: number
                    description: ' '
                  realScore:
                    type: number
                    description: ' '
                  detectSquareErr:
                    type: number
                    description: ' '
                required:
                  - result
                  - fakeScore
                  - realScore
                  - detectSquareErr
              examples:
                결과:
                  value:
                    result: 1
                    fakeScore: 0.476456
                    realScore: 0.527431
                    detectSquareErr: 0
        '400':
          $ref: '#/components/responses/400'
        '401':
          description: |-
            Unauthorized

            허가되지 않은 사용자의 접근
        '409':
          $ref: '#/components/responses/409'
        '500':
          description: |-
            Internal Server Error

            서버가 유지보수 중이거나 응답할 수 없는 상태
      description: ~~ ~~
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                id_liveness_type:
                  type: integer
                  description: ''
                  enum:
                    - 1
                    - 2
                image:
                  type: string
                  minLength: 1
                  description: |-
                    이미지를 base64로 인코딩 한 스트링

                    지원포맷: jpg(jpeg), png, tif(tiff), bmp, gif
              required:
                - image
            examples:
              Base64 Example:
                value:
                  id_liveness_type: 1
                  image: iVBORw0KGgoAAAANSUhEUgAACbEAAA2zCAYAAADce6KLAAAA....
              URL Example:
                value:
                  id_type: jumin
                  image: 'https://www.cometrue.ai/data/license.jpg'
                  is_url: true
        description: ''
      security:
        - api_key: []
      x-internal: false
    parameters: []
components:
  schemas: {}
  securitySchemes:
    api_key:
      name: api_key
      type: apiKey
      in: query
      description: api.cometrue.ai에서 발급받은 API key
  responses:
    '400':
      description: |
        Bad Request

        사용자가 키를 잘못 입력하였거나, 값에 문제가 있을때

        <details markdown="1">
        <summary>에러메세지</summary>
        "image: not provided"<br>
        "image base64 decode error"<br>
        "Image cannot be read"<br>
        "Image is too small to process"<br>
        "image: property in this field does not match. base64 or url."<br>
        "Image is empty"<br>
        </details>
      content:
        application/json:
          schema:
            description: ''
            type: object
            properties:
              message:
                type: string
                minLength: 1
            required:
              - message
          examples:
            image not given:
              value:
                message: 'image: not provided'
            base64 decoding of the image failed:
              value:
                message: image base64 decode error
            Image not readable:
              value:
                message: Image cannot be read
            Query image is too small to process:
              value:
                message: Image is too small to process
            image property does not match:
              value:
                message: 'image: property in this field does not match. base64 or url.'
            image empty:
              value:
                message: Image is empty
    '409':
      description: |-
        Conflict

        서버에서의 처리 중 에러

        <details markdown="1">
        <summary>에러메세지</summary>
        "Onnx runtime error: 100"<br>
        "Std Exception: 101"<br>
        "OpenCV error: 100"<br>
        "text detection error: 201": cannot find text<br>
        "text detection error: 202": Vertex detection error<br>
        "text detection error: 203": cannot find square<br>
        "text detection error: 204": not enough to be square<br>
        "text detection error: 206": not enough similar area<br>
        "text detection error: 207": not enough contour<br>
        "text detection error: 208": not enough group<br>
        "object detection error: 209": cannot find object<br>
        "Json decode error"
        </details>
      content:
        application/json:
          schema:
            description: ''
            type: object
            properties:
              message:
                type: string
            required:
              - message
          examples:
            Vertex detection error:
              value:
                message: 'text detection error: 202'
            Text detection error:
              value:
                message: text detection error
            //OCR error:
              value:
                message: text recognition error
            //Matching error:
              value:
                message: matching error
            onnxexception:
              value:
                message: 'Onnx runtime error: 100'
            stdexception:
              value:
                message: 'Std Exception: 101'
            cvexception:
              value:
                message: 'OpenCV error: 100'
            cannot find text:
              value:
                message: 'text detection error: 201'
            cannot find square:
              value:
                message: 'text detection error: 203'
            not enough to be square:
              value:
                message: 'text detection error: 204'
            not enough contour:
              value:
                message: 'text detection error: 207'
            not enough group:
              value:
                message: 'text detection error: 208'
            cannot find object:
              value:
                message: 'object detection error: 209'
            json decode error:
              value:
                message: Json decode error
            not enough similar area:
              value:
                message: 'text detection error: 206'
