openapi: 3.0.0
info:
  title: 표 OCR
  version: '1.0'
  description: 이미지에서 표를 검출하여 텍스트로 제공합니다.
  contact:
    email: ask@comtrue.com
    url: 'https://cometrue.ai'
    name: cometrue.ai AI API
  termsOfService: 'https://cometrue.ai/index.php/ai-api-terms-of-service/'
servers:
  - {}
paths:
  /api/v1/table/ocr:
    post:
      summary: 표 OCR
      operationId: post-tableocr
      responses:
        '200':
          description: |-
            OK

            정상응답
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    result:
                      - table_index: 0
                        cells:
                          - x: 1
                            'y': 3
                            str: []
                          - x: 2
                            'y': 1
                            str: []
                          - x: 2
                            'y': 2
                            str:
                              - longterm
                              - debtrating
                              - (s.ermioodys)
                          - x: 2
                            'y': 3
                            str:
                              - valuationpercentage
                          - x: 3
                            'y': 1
                            str:
                              - axrwcash
                          - x: 4
                            'y': 1
                            str:
                              - (krwcashdeposit.openedand
                              - maintainedwithaqualifiedfinancial
                              - institutiondefinedinannex4ofthe
                              - idetail.edregulationsof
                              - 'on'
                              - the
                              - regul.ations
                              - investent
                              - financial.
                              - business1
                          - x: 4
                            'y': 2
                            str:
                              - aa-a
                              - laa-a2
                          - x: 4
                            'y': 3
                            str:
                              - '1009'
                          - x: 3
                            'y': 2
                            str:
                              - notapplicable
                          - x: 3
                            'y': 3
                            str:
                              - 9x00r
                          - x: 5
                            'y': 1
                            str:
                              - (xrwdcbtsccuriticsissuedbythc
                              - govermentorthcrepublicofkorea
                              - (rvxrwdebtsecuritiesissuedbythe
                              - bankofkorca
                          - x: 5
                            'y': 2
                            str:
                              - notapplicable
                          - x: 5
                            'y': 3
                            str:
                              - residual
                              - maturity
                              - years.
                              - '51,99.59'
                              - '21,55.98입.'
                              - 35.969.
                          - x: 6
                            'y': 1
                            str:
                              - (vkrwdebtsecuritiesissuedor
                              - guaranteedinfllamountbyapublic
                              - corporationwhoselossinstitutionally
                              - coveredbythegovermentaccording
                              - toaspecialact.
                          - x: 6
                            'y': 2
                            str:
                              - aa-bb.
                              - laa-ba3
                          - x: 6
                            'y': 3
                            str:
                              - kesidual
                              - maturity
                              - years.
                              - '51,999'
                              - '21,5596원'
                              - '25.929'
                          - x: 7
                            'y': 1
                            str:
                              - (vxrwdcbtsccuriticsissuedbya
                              - qualifiedfinanciatinstitutiondefined
                              - inannex4oftheidetail.ed
                              - the
                              - regul.ations
                              - regulationsonfinancial
                              - investmentbusiness1
                          - x: 7
                            'y': 2
                            str:
                              - a4-a4-
                              - taaa-aa3
                          - x: 7
                            'y': 3
                            str:
                              - kesidual
                              - maturity
                              - years.
                              - '-,9993'
                              - '31,5596'
                              - 25.929.
                          - x: 8
                            'y': 2
                            str:
                              - 4-a
                              - 11-42
                          - x: 8
                            'y': 3
                            str:
                              - kesidual
                              - maturity
                              - years.
                              - '51,989'
                              - '기1,5594입'
                              - 25.889.
                      - table_index: 1
                        cells:
                          - x: 2
                            'y': 2
                            str:
                              - longterm
                              - debtrating
                              - (sepmmoodys)
                          - x: 2
                            'y': 3
                            str:
                              - valuationpercentage
                          - x: 3
                            'y': 2
                            str: []
                          - x: 3
                            'y': 3
                            str:
                              - 25-96일
                          - x: 4
                            'y': 2
                            str:
                              - 4-bbe-
                              - 11-baa3
                          - x: 4
                            'y': 3
                            str:
                              - ojt6isx
                              - '4651'
                              - '9666.15'
                              - ssraf
                              - kuueur
                              - 피
                              - tenprsay
                properties:
                  result:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        table_index:
                          type: number
                          description: 표 번호
                        cells:
                          type: array
                          uniqueItems: true
                          minItems: 1
                          description: 셀
                          items:
                            type: object
                            properties:
                              x:
                                type: number
                                description: 셀의 행번호
                              'y':
                                type: number
                                description: 셀의 열번호
                              str:
                                type: array
                                description: 텍스트
                                items:
                                  type: string
                            required:
                              - x
                              - 'y'
                      required:
                        - table_index
                required:
                  - result
              examples:
                결과:
                  value:
                    result:
                      - table_index: 0
                        cells:
                          - x: 1
                            'y': 3
                            str: []
                          - x: 2
                            'y': 1
                            str: []
                          - x: 2
                            'y': 2
                            str:
                              - longterm
                              - debtrating
                              - (s.ermioodys)
                          - x: 2
                            'y': 3
                            str:
                              - valuationpercentage
        '400':
          $ref: '#/components/responses/400'
        '401':
          description: |-
            Unauthorized

            허가되지 않은 사용자의 접근
        '409':
          $ref: '#/components/responses/409'
        '500':
          description: |-
            Internal Server Error

            서버가 유지보수 중이거나 응답할 수 없는 상태
      description: |-
        이미지에서 표를 인식하여 텍스트를 검출하고, 표 번호와 셀의 행과 열 번호를 포함하여 리스트로 제공합니다.

        (이미지는 회전되지 않은 상태이어야 합니다.)
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                image:
                  type: string
                  minLength: 1
                  description: |-
                    이미지를 base64로 인코딩 한 스트링

                    지원포맷: jpg(jpeg), png, tif(tiff), bmp, gif
              required:
                - image
            examples:
              Base64 Example:
                value:
                  image: iVBORw0KGgoAAAANSUhEUgAACbEAAA2zCAYAAADce6KLAAAA....
              URL Example:
                value:
                  id_type: jumin
                  image: 'https://www.cometrue.ai/data/license.jpg'
                  is_url: true
        description: ''
      security:
        - api_key: []
      x-internal: false
    parameters: []
components:
  schemas: {}
  securitySchemes:
    api_key:
      name: api_key
      type: apiKey
      in: query
      description: api.cometrue.ai에서 발급받은 API key
  responses:
    '400':
      description: |
        Bad Request

        사용자가 키를 잘못 입력하였거나, 값에 문제가 있을때

        <details markdown="1">
        <summary>에러메세지</summary>
        "image: not provided"<br>
        "image base64 decode error"<br>
        "Image cannot be read"<br>
        "Image is too small to process"<br>
        "image: property in this field does not match. base64 or url."<br>
        "Image is empty"<br>
        </details>
      content:
        application/json:
          schema:
            description: ''
            type: object
            properties:
              message:
                type: string
                minLength: 1
            required:
              - message
          examples:
            image not given:
              value:
                message: 'image: not provided'
            base64 decoding of the image failed:
              value:
                message: image base64 decode error
            Image not readable:
              value:
                message: Image cannot be read
            Query image is too small to process:
              value:
                message: Image is too small to process
            image property does not match:
              value:
                message: 'image: property in this field does not match. base64 or url.'
            image empty:
              value:
                message: Image is empty
    '409':
      description: |-
        Conflict

        서버에서의 처리 중 에러

        <details markdown="1">
        <summary>에러메세지</summary>
        "Onnx runtime error: 100"<br>
        "Std Exception: 101"<br>
        "OpenCV error: 100"<br>
        "text detection error: 201": cannot find text<br>
        "text detection error: 202": Vertex detection error<br>
        "text detection error: 203": cannot find square<br>
        "text detection error: 204": not enough to be square<br>
        "text detection error: 206": not enough similar area<br>
        "text detection error: 207": not enough contour<br>
        "text detection error: 208": not enough group<br>
        "object detection error: 209": cannot find object<br>
        "Json decode error"
        </details>
      content:
        application/json:
          schema:
            description: ''
            type: object
            properties:
              message:
                type: string
            required:
              - message
          examples:
            Vertex detection error:
              value:
                message: 'text detection error: 202'
            Text detection error:
              value:
                message: text detection error
            //OCR error:
              value:
                message: text recognition error
            //Matching error:
              value:
                message: matching error
            onnxexception:
              value:
                message: 'Onnx runtime error: 100'
            stdexception:
              value:
                message: 'Std Exception: 101'
            cvexception:
              value:
                message: 'OpenCV error: 100'
            cannot find text:
              value:
                message: 'text detection error: 201'
            cannot find square:
              value:
                message: 'text detection error: 203'
            not enough to be square:
              value:
                message: 'text detection error: 204'
            not enough contour:
              value:
                message: 'text detection error: 207'
            not enough group:
              value:
                message: 'text detection error: 208'
            cannot find object:
              value:
                message: 'object detection error: 209'
            json decode error:
              value:
                message: Json decode error
            not enough similar area:
              value:
                message: 'text detection error: 206'
